godotengine/tps-demo

level/level.gd

The wrong setting (ssao_quality instead of resolution) was used to determine which resolution should be used in the level scene.

Fixed resolution settings

---

level/level.gd

Currently choosing between the high and low value of the SSAO-Option doesn't make any difference in the settings.
With this change the world environment's settings will be set.

Settings: extended SSAO quality settings

---

player/bullet.tscn

- Don't bake GI for bullet lights to improve performance and avoid flickering
- Use less detailed spheres for the main bullet and its trail
- Use smaller lights to be more subtle, also making shadow acne less visible
- Tweak the explosion effect to be more subtle

Improve bullet particle effects

---

default_bus_layout.tres
default_env.tres
door/door.gd
enemies/red_robot/red_robot.gd
level/level.gd
menu/menu.gd
menu/menu.tscn
menu/settings.gd
player/bullet.gd
player/player.gd

This PR changes the scripts to conform to the [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html), among other small improvements. List of changes (there may be more that aren't listed here, it's hard to keep track):
* Removed stray indentation.
* Removed empty functions.
* Removed unnecessary parenthesis.
* Exactly two empty lines between methods.
* Proper spacing around commas and operators. Previously it was wrong almost everywhere.
* Comments now start with a space and capital letter and end with a period.
* Change order of constants, variables, and methods to match the style guide.
* Where appropriate, use enums instead of constants.
* Use `Vector3.UP` instead of `Vector3(0,1,0)`
* Some logic simplification, like …

Update scripts to conform to the GDScript style guide

---

level/level.tscn
level/shader_cache.gd
player/bullet.tscn
player/bullet_material.tres
player/player.tscn

This is partially a rebase and partially a rewrite of #24, except only the bullet shader caching, it does not include any fading. Instead of making it part of the player, I made a self-deleting node. The children of this node are at the origin, which is within the camera frustum of the player's start location.
One other minor change, I renamed "robot" to "player" in `player.tscn`.
I assigned the label "bug" because I think the stuttering is a bug to begin with. Let me know if this label isn't appropriate here.

Pre-compile Bullet shader to avoid stutter on first use

---

level/level.gd
menu/menu.gd
player/player.gd
project.godot

* The D-pad is now supported for movement.
* Increase the sensitivity by 3x for rotating the camera with controllers. It was a bit slow before.
* Reduce the sensitivity while aiming to passively assist with aiming (0.5 multiplier). I added this effect with the mouse as well, but it's not as strong (0.75 multiplier).
* Shrink the deadzone to 0.2, since 0.5 seemed to be way too high for the Steam controller.
I also fixed a minor issue with AAQuality.DISABLED and some style problems.

Tweak controller support

---

default_env.tres

The 3.1/3.2 environment is far less blue. The update only requires removing some of the values, so that Godot's new default values are used. This is only visible in the editor, and isn't used in-game.

Update default_env.tres to the Godot 3.1/3.2 default environment

---

level/debug.gd
level/level.tscn
project.godot

Adds some debug text in the corner of the screen, which includes FPS, VSync status, and memory usage, available by pressing F3. This can be used to benchmark the demo or to test Godot.
I'm backporting this from #67 because I think it would be useful for benchmarking and comparing.

[3.2.1] Implement some in-game debug text

---

level/debug.gd
level/geometry/scenes/core.tscn
level/shader_cache.gd

* Add an underscore to debug's delta.
* Change shader cache to set volume to -INF instead of deleting the audio node. I went on a truly bizzare wild goose chase and discovered that an alternative solution is to delete the `CentralCylinder3` node in `core.tscn` (wtf‽). I'm still confused as to how that works.

Fix some minor problems

---

player/bullet/bullet.tscn

Previously, this could affect your aim in a minor way, since if you aimed at a bullet, it counted. Now, if you aim at a bullet, it won't count that, and you will actually be aiming at the object behind the bullet.

Prevent aiming at other bullets by setting their collision layer to zero

---

player/player.gd

This is necessary, otherwise the frame after jumping it's possible that
on_air will be unset due to airborne time being less than
MIN_AIRBORNE_TIME. This causes jumps to feel sluggish since the player's
horizontal speed gets lowered.

On jump input, immediately increase airborne time to MIN_AIRBORNE_TIME.

---

level/level.gd
main/main.gd
menu/menu.gd
menu/menu.tscn
menu/settings.gd

The default level is High, which is equivalent to the previous glow setting used (bicubic upscaling enabled).
Low keeps glow enabled but disables bicubic upscaling. Disabled disables glow entirely.
The setting is called "bloom" as it's a more common term in gaming, even though the Environment parameter is called "glow".

Add a bloom quality setting

---

enemies/red_robot/red_robot.gd
level/level.gd
menu/settings.gd

I copied a few of the tweaks from #88. These improve 4.0 compatibility, but still work great in 3.2.

Add commas and tweak scripts for better compatibility with Godot 4

---

LICENSE.md
README.md

This PR updates the README for Godot 3.3 and a few other misc things.
After this PR, there will be a 3.2 branch, and the master branch of the TPS demo will be targeting Godot 3.3.x.

Update README for the new 3.2 branch

---

README.md

This PR updates the README of the 3.2 branch to reflect the changes in #98 and the other PRs linking to there. This is a very small change over #98, it just bolds and italicizes ***3.2***, and changes the download link to point to 3.2 instead of master.

[3.2] Update README for the new 3.2 branch

---

project.godot

This feature is enabled by default in Godot 3.1 and later.
*Click to view at full size.*

Enable font oversampling for better text rendering at high resolutions

---

player/player.gd
player/player.tscn

- Fade the ColorRect out after being teleported back. Previously, only a fade-in effect was present.
- Draw the ColorRect in front of the crosshair to hide it during the fade (if aiming while falling).

Improve fall teleport fade effect

---

level/level.gd
menu/menu.gd
menu/menu.tscn
menu/settings.gd

Disabling shadows reduces the number of draw calls significantly, which improves rendering performance a lot.
Since the demo doesn't have too many bright point lights, the visual difference isn't that noticeable (except when walking under a light).
This will come particularly handy on integrated graphics and on mobile (once https://github.com/godotengine/tps-demo/pull/118 is merged).
FPS over time when following the path from spawn to the reactor room. Using the default graphics settings in 2560×1440 on a GeForce GTX 1080:

Add a setting to disable real-time light shadows

---

level/level.tscn

This uses occluder shape quads (introduced in Godot 3.5).
From my testing, this doesn't improve performance much during actual gameplay in GLES3 (since there's already a depth prepass doing its job). However, occluder shapes help significantly in GLES2 (especially in the reactor room), as GLES2 lacks a depth prepass.

Add occluder shapes to improve performance

---

level/level.gd
menu/menu.gd
project.godot

The menu and game no longer have black bars when using an aspect ratio wider than 16:9. This works both with native and sub-native resolutions.

Use the `expand` stretch aspect to support arbitrary aspect ratios

---

level/forklift/flying_forklift.tscn
level/geometry/scenes/core.tscn
project.godot

Like https://github.com/godotengine/tps-demo/pull/130, this enables another new feature in 3.5.
Physics interpolation was disabled on the reactor core's particles as it caused visual glitches (and is not needed there anyway). It was also disabled on the flying forklift as it's actually moved in `_process` (the engine was printing warnings about it).
To test this, run the demo with the lowest possible settings and see if overall smoothness improves. Note that player/enemy animations are not interpolated (only their movement is), so they remain locked at their 60 Hz rate. In practice, this usually looks good enough. Still, I wonder how these can be interpolated too :slightly_smiling_face: 
cc @lawnjelly

Enable physics interpolation

---

project.godot

This uses a more realistic light attenuation model, similar to the one used in 4.0.alpha.
The effect isn't very noticeable on the scene, except when firing the weapon.

Enable physical light attenuation

---

player/player.tscn

- Increase movement speed while walking by 10%.
- Increase movement speed while aiming by 20%.
- Increase blend transition time from 0.15 to 0.20 seconds for more natural transitions when aiming or jumping.

Increase player movement speed slightly

---

enemies/red_robot/laser/impact_effect/impact_effect.tscn
enemies/red_robot/parts/part_disappear_effect/part_disappear.tscn
enemies/red_robot/red_robot.tscn
player/bullet/bullet.tscn
player/player.tscn

Can be merged independently of https://github.com/godotengine/tps-demo/pull/131.
This improves performance when the player or enemy fires their weapon, or when an enemy dies. This may also help reduce shader compilation stutter on the first playthrough (even when asynchronous compilation is enabled).
There is usually no noticeable visual difference.

Disable shadow casting for short-lived effects

---

project.godot

~~Do not merge until Godot 3.5.1 is released, as it includes https://github.com/godotengine/godot/pull/64096 which is required for this PR to work well.~~
**Edit:** 3.5.1 is now released, so this can be merged :slightly_smiling_face: 
This mitigates shader compilation stutter, especially after an initial playthrough thanks to caching.
This requires Godot 3.5 or later to have an effect.

Enable asynchronous shader compilation and caching

---

enemies/red_robot/red_robot.gd

When the player first enters a red robot's detection collider, it drops to the floor and then approaches the player.  This is because they are placed slightly above the ground in `level.tscn`, as it is somewhat hard to get just perfect.
I added a line in `red_robot.gd` to apply gravity while it is idling, so it doesn't just hover there.

Apply gravity to Red Robot while idle

---

level/level.tscn

The occluder shape placement was too aggressive, not taking into account the fact that the camera can be brought flush to the floor by the player when looking upwards.
This closes https://github.com/godotengine/tps-demo/issues/148.

Fix occluder shape placement in the level causing too much occlusion

---

README.md

`4.0-dev` version of https://github.com/godotengine/tps-demo/pull/159 (identical to `master`, as the controls are the same).
This closes https://github.com/godotengine/tps-demo/issues/157.

Add controls to the README (4.0-dev)

---

player/player.tscn

This makes initial flickering and stuttereing caused by asynchronous shader compilation less noticeable.

Fade the view when loading the level scene

---

menu/menu.gd

With threaded loading you can't try to get the result of a load request multiple times (requests and gets must be balanced). If anything, this code should have called `load()` in the positive branch of the `if`, which would return the existing instance of the resource from the cache. However, that's already what would happen anyway in a threaded load, so there's little to no point in handling it specially.
Furthermore, this project is not doing anything to keep the resource in the cache so the check will always fail anyway.

Remove superfluous and wrong logic to reuse cached load

---

.editorconfig
enemies/red_robot/red_robot.tscn
menu/menu.gd
player/bullet/bullet.tscn
player/bullet/effect/BlastMaterial.tres
project.godot

Explanation courtesy of @DarioSamo:
This was an attempt by the game to cache the pipelines ahead of time for the bullet. However, the title screen does not use SDFGI or VoxelGI, so the ubershader pipeline pre-compilation is not detecting it should create these pipelines.
The extra two to four pipelines we're seeing on the first shot are the new pipelines encountered due to the fact the effect only gets enabled when starting the game, but the instancing of this bullet ahead of time is not done there instead.
Merely instancing the bullet scene as hidden fixes this issue immediately, as hidden surfaces are added to the cache.
A side effect of this change is that `menu.tscn` no longer needs to store a lot of properties, so it becomes a lot smaller and should load faster too.
**This change …

Hide menu BackgroundCache node to fully benefit from async. pipeline compilation

---

level/geometry/environment.tres
level/level.gd
menu/menu.gd
menu/menu.tscn
player/bullet/bullet.tscn
project.godot

This allows running the TPS demo on a greater range of devices and platforms, while also allowing its use for GLES2 renderer testing.
Several automatic adjustments are made to ensure it looks as good as possible (within the limitations of GLES2 and the lack of baked lightmaps).
Some particles are currently missing and would need CPUParticles fallbacks to be added to become visible again.
**Edit:** Bullet bodies/trails are now visible in GLES2 as this PR converts them to CPUParticles. They look identical to before in GLES3.
Bullet explosions are still missing, but they use custom particle shaders so a complete rewrite would be required.
To test this locally, start the project with the `--video-driver GLES2` command line argument (or add `--video-driver GLES2` to the **Main Run Args** …

[3.x] Allow falling back to GLES2

---

main/main.gd
project.godot

This has some benefits over V-Sync:
- TPS demo is prone to stuttering and unstable frametimes. Disabling V-Sync helps make those issues less noticeable.
- Reduced input latency is useful for games with mouse aiming.
This comes at the cost of tearing, but it's usually not too noticeable in the TPS demo. Eventually, an option to re-enable V-Sync could be added to the options menu.
I recommend testing this PR on your own machine and see how it behaves in practice. Even on high-end GPUs, it often makes the demo feel smoother as you walk around the scene.

[3.x] Disable V-Sync and use optimized FPS limit
